### ISSUE TITLE
Optimize /api/creators/ endpoint

### ISSUE THREAD

**Issue by ExtReMLapin** [OpenYiff/Kemono2#119]
`/api/creators/` 

Is slow as hell for the following reason : 
It tries to serialize 16k entries with it's keys on each API call

You need to either implement a very high performance json lib or just cache the result with any flask caching module.

Or you can make an endpoint for the search, instead of sending the whole list each time.

**Comment by ExtReMLapin** [comment]
If you send me a DB (without the medias , but only the text) i'll be happy to do optimizations on it

**Comment by ZeeWanderer** [comment]
Maybe switch to CSV? Creators' data format is a list of simple single level objects, ideal for CSV. It should be at least an order of magnitude faster. 
As far as i know there was search endpoint but there were performance issues.

**Comment by ExtReMLapin** [comment]
You understand the point of  JSON and the fact the idea is to use it in Javascript, right ?

**Comment by ExtReMLapin** [comment]
Actually, it's slow because of download time 
![][https://i.imgur.com/d7440CQ.png)

So making a search enpoint migh be better

**Comment by ZeeWanderer** [comment]
If we were to consider CSV seriously then using it in JS is trivial provided you use a lib. I actually checked the performance, that is to say i converted json form creators' endpoint to CSV and then used [an online lib demo](https://www.papaparse.com/demo) to parse it. ~30-50 ms is good, and there supposedly is fast mode which is not enablable in demo. The actual use case problem is that you get arrays not objects, but that just requires some changes in filtering logic - you find the index of the field you are filtering by in the header row and then use that index to filter values in arrays. Provided server can efficiently write CSV you should actually win some since parsing CSV is easier than json. 

Download being the bottleneck is a given, for me it is usually about 3 seconds.

Search endpoint was disabled for a reason, and i doubt that changed. You'd have to wait for a response from an actual dev.

**Comment by msjea** [comment]
Hello, I'm having a issue importing logs from someones pateron despite doing everything correctly. It keeps on saying in the second-row: "Error connecting to cloudscraper. Please try again."

**Comment by ExtReMLapin** [comment]
> Hello, I'm having a issue importing logs from someones pateron despite doing everything correctly. It keeps on saying in the second-row: "Error connecting to cloudscraper. Please try again."

Wrong issue buddy

**Comment by kemono-bugs** [comment]
> `/api/creators/`
> 
> Is slow as hell for the following reason :
> It tries to serialize 16k entries with it's keys on each API call
> 
> You need to either implement a very high performance json lib or just cache the result with any flask caching module.
> 
> Or you can make an endpoint for the search, instead of sending the whole list each time.

In production, kemono.party already caches the result with Varnish.
But it could be more efficient... maybe some sort of incremental refreshing is in order.

**Comment by kemono-bugs** [comment]
> If you send me a DB (without the medias , but only the text) i'll be happy to do optimizations on it

`rsync://rsync.kemono.party/kemonodb-public`

**Comment by ImportTaste** [comment]
Additionally, adding a parameter to display extracted comments would be appreciated, since some artists like to post links in there.

**Comment by ExtReMLapin** [comment]
It seems the issue is fixed as the endpoint is now cached
